# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: carEXIT
description: > # this means to ignore newlines until "baseurl:"
    carEXIT
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

includes_dir: _includes

# Contact values.
email: info@carexit.org
twitter_username: mradgbln
facebook_page: mitRADgelegenheit

languages:
  - de
  - br
  - gr

# Build settings
markdown: kramdown
exclude:
  - Gem*
  - vendor
  - Readme*
